---
- name: moodle setup
  hosts: all
  become: true

  tasks:

  - name: update server
    apt: update_cache=yes

  - name: Add PHP 7 PPA Repo
    become: true
    apt_repository:
      repo: 'ppa:ondrej/php'
      codename: trusty #<<<

  - name: install git, apache and moodle dependencies
    apt:
     name: "{{ packages }}"
    vars:
     packages:
     - git-core
     - apache2
     - mysql-client
     - mysql-server
     - graphviz
     - aspell
     - ghostscript
     - clamav
     - php7.2-curl
     - php7.2-gd
     - php7.2-intl
     - php7.2-mysql
     - php7.2-xml
     - php7.2-xmlrpc
     - php7.2-ldap
     - php7.2-zip
     - php7.2-soap
     - php7.2-mbstring
     - php7.2-pspell
     - php7.2-cli


